//! The slither IK handshake on hiss's `noise!`-generated sans-io state
//! machines, and the WireGuard-style initiation defences layered around it.
//!
//! The handshake is declared once, in Noise's own notation, by the
//! [`hiss::noise!`] invocation below; hiss generates fixed-size, no-I/O state
//! machines (every message is a `[u8; N]`), so slither frames the messages
//! into its packets directly — no buffer adapters, no blocking driver.
//!
//! # The timestamp rides the encrypted msg1 payload
//!
//! WireGuard puts a monotonic timestamp inside the encrypted handshake-init
//! payload to defeat initiation replay, and slither does exactly the same: the
//! pattern declares a 12-byte **application payload** on msg1 (the `[12]`
//! suffix), the initiator supplies the timestamp to
//! [`write_message_1`](IKInitiatorMsg1::write_message_1), and the responder's
//! read recovers it. On IK msg1 the payload tail is keyed (encrypted after the
//! `e, es, s, ss` tokens), so the timestamp is confidential to the holder of
//! the responder's static — a passive observer never sees the initiator's
//! clock — and a tampered payload ciphertext fails the tail's AEAD tag,
//! failing the handshake. The prologue is the fixed [`PROLOGUE`] constant.
//! Per initiator static the responder keeps the greatest timestamp accepted
//! ([`TimestampGuard`]) and rejects non-greater values.
//!
//! # The allow-list is the read's verification closure
//!
//! [`accept_init`] verifies mac1 (the DoS gate — before any DH), then reads
//! msg1 through the generated
//! [`read_message_1_with`](IKResponderMsg1::read_message_1_with) variant: the
//! initiator's **claimed** static is handed to the closure as soon as `s`
//! decrypts — after the `es` DH, **before** `ss` — and the closure is the
//! allow-list. An unlisted claim is rejected there
//! (`HandshakeError::PeerRejected`, surfaced as [`HsError::Unlisted`]) at the
//! ruled cost of exactly one DH, with no `ss`, no timestamp decryption, and
//! no msg2 (the maintainer, 2026/07/16). At that point the identity is
//! *claimed, not yet proven* — hiss's documented contract for the `_with`
//! reads — so rejecting is always safe; possession of a *listed* claim is
//! proven inside the same accepted read by `ss` and the tail's AEAD tag
//! (a forger of a listed key costs the `ss` DH too, then fails there —
//! WireGuard's exact shape). An accepted read pauses on the [`RespAccept`]:
//! the caller consults the [`TimestampGuard`] and either
//! [`RespAccept::accept`]s (writing msg2, establishing the session) or
//! **drops** the accept — rejecting the peer with no msg2, WireGuard's
//! silent reject.

use std::collections::{HashMap, HashSet};

use hiss::curve::p256::{P256r1PrivateKey, P256r1PublicKey};
use hiss::noise::{Blake2b, ChaChaPoly, P256};
use hiss::noise::{DatagramRecv, DatagramSend, HandshakeError, SessionId};
use hiss::provider::{CryptoKeyProvider, DhProvider, EphemeralOnly};
use rand_chacha::ChaCha20Rng;
use rand_core::{Rng, SeedableRng};

use crate::SlitherChannel;
use crate::mac;
use crate::session::REKEY_EPOCH_MSGS;
use crate::wire::{
    IK_MSG1_LEN, IK_MSG2_LEN, INIT_PACKET_LEN, InitHeader, PROLOGUE, RESP_PACKET_LEN, RespHeader,
    Timestamp,
};

use packtool::{Packed, View};

hiss::noise! {
    /// The slither handshake, generated by [`hiss::noise!`]: IK over the
    /// pinned suite, with the 12-byte initiation timestamp declared as
    /// msg1's application payload (the `[12]` suffix).
    ///
    /// The pattern is named `IK` **deliberately**: the pattern name is part
    /// of the Noise protocol identity (the transcript hashes
    /// `Noise_IK_P256_ChaChaPoly_BLAKE2b`), so this name — and nothing else —
    /// keeps the generated machines byte-compatible with slither's ratified
    /// wire. Re-exported at the crate root as
    /// [`SlitherChannel`](crate::SlitherChannel).
    pub IK<P256, ChaChaPoly, Blake2b> {
        <- s
        ...
        -> e, es, s, ss [12]
        <- e, ee, se
    }
}

impl IK {
    /// The AEAD tag size in bytes (`ChaChaPoly`) — mirrors the classic
    /// descriptor's const so [`wire`](crate::wire) derives its sizes from
    /// [`SlitherChannel`] unchanged.
    pub const TAG_SIZE: usize = <ChaChaPoly as hiss::noise::Cipher>::TAG_SIZE;

    /// The serialised (uncompressed SEC1) public-key size in bytes (P-256) —
    /// mirrors the classic descriptor's const, for [`wire`](crate::wire).
    pub const PUBLIC_KEY_SIZE: usize = <P256 as hiss::curve::Curve>::PUBLIC_KEY_SIZE;
}

// The verdict-deciding pins: the macro-derived message sizes must equal the
// ratified wire constants. If these ever disagree, the wire has moved — the
// crate fails to compile rather than shipping a different protocol.
const _: () = assert!(IK::MSG1_SIZE == IK_MSG1_LEN);
const _: () = assert!(IK::MSG2_SIZE == IK_MSG2_LEN);

// ── Byte offsets within a handshake packet ────────────────────────────────────

/// Offset of the IK msg1 within a HandshakeInit packet.
const INIT_MSG_START: usize = InitHeader::SIZE;
/// Offset of the mac1 within a HandshakeInit packet (also the mac1 preimage len).
const INIT_MAC_START: usize = INIT_MSG_START + IK_MSG1_LEN;
/// Offset of the IK msg2 within a HandshakeResp packet.
const RESP_MSG_START: usize = RespHeader::SIZE;
/// Offset of the mac1 within a HandshakeResp packet (also the mac1 preimage len).
const RESP_MAC_START: usize = RESP_MSG_START + IK_MSG2_LEN;

// ── Errors ────────────────────────────────────────────────────────────────────

/// A handshake failure. Every variant is, for the endpoint actor, a **silent
/// drop** — a malformed, unauthenticated, forged, or merely unlisted packet
/// never disturbs a live session and never surfaces to the peer.
#[derive(Debug, thiserror::Error)]
pub enum HsError {
    /// A Noise handshake token failed — a forged, tampered (including a
    /// tampered timestamp-payload ciphertext), or wrong-key message. The
    /// `hiss` cause is preserved as the message.
    #[error("noise handshake failed: {0}")]
    Crypto(String),
    /// The packet was structurally malformed, the wrong length, addressed to a
    /// different session, or failed the mac1 gate — dropped before (or instead
    /// of) any curve work. The `&str` names which check tripped, for tracing.
    #[error("packet dropped: {0}")]
    Drop(&'static str),
    /// The initiator's claimed static is not on the allow-list — rejected by
    /// the verification closure at the ruled one-DH cost (no `ss`, no
    /// timestamp decryption, no msg2).
    #[error("initiator static not on the allow-list")]
    Unlisted,
}

impl From<HandshakeError> for HsError {
    fn from(error: HandshakeError) -> Self {
        match error {
            // The only source of `PeerRejected` in slither is `accept_init`'s
            // allow-list closure.
            HandshakeError::PeerRejected { .. } => HsError::Unlisted,
            other => HsError::Crypto(other.to_string()),
        }
    }
}

// ── The identity seam (a fresh provider + static per handshake) ───────────────

/// The static identity that drives slither's handshakes.
///
/// Each handshake needs a **fresh** ephemeral provider (re-using one would reuse
/// the IK ephemeral) plus a fresh owned copy of the long-term static private key
/// (the `s` token consumes it by value). This trait supplies both, alongside
/// the static's public half. It is generic over the provider so a
/// hardware-held static (an Apple Secure Enclave P-256 key, one day) could drive
/// slither with no wire change — the brief's "generic over `DhProvider<P256>`"
/// intent, expressed as a factory because a fresh-ephemeral handshake **consumes**
/// a provider.
pub trait Identity {
    /// The per-handshake Noise provider.
    type Provider: DhProvider<P256> + 'static;

    /// A fresh provider — fresh ephemeral entropy — for one handshake.
    fn provider(&mut self) -> Self::Provider;

    /// A fresh owned copy of the static private key, consumed by one
    /// handshake's `s` token (the writer's argument, or the responder
    /// constructor's).
    fn static_secret(&mut self) -> <Self::Provider as CryptoKeyProvider<P256>>::PrivateKey;

    /// The static public key — the peer-facing identity and the mac1 keying key.
    fn static_public(&self) -> P256r1PublicKey;
}

/// A pure-software slither identity: a P-256 static scalar plus a master CSPRNG
/// from which a fresh ephemeral seed is drawn per handshake.
///
/// The static private key is never persisted here beyond its raw scalar bytes; it
/// is rebuilt from them per handshake (the scalar was validated at construction,
/// so the rebuild is infallible — mirroring `bubble`'s `software_static`).
pub struct SoftwareIdentity {
    scalar: [u8; 32],
    public: P256r1PublicKey,
    master: ChaCha20Rng,
}

impl SoftwareIdentity {
    /// Build a software identity from a 32-byte P-256 **static scalar**, seeding
    /// the per-handshake ephemeral CSPRNG from the caller-supplied `master` RNG.
    ///
    /// An out-of-range scalar (`0` or `>= n`) is rejected outright — this is a
    /// long-term identity key, not a seed, so it is used verbatim.
    pub fn from_scalar(scalar: [u8; 32], master: ChaCha20Rng) -> Result<Self, HsError> {
        let secret = P256r1PrivateKey::from_bytes(scalar)
            .map_err(|_| HsError::Drop("invalid static scalar"))?;
        let public = secret.public();
        Ok(Self {
            scalar,
            public,
            master,
        })
    }
}

impl Identity for SoftwareIdentity {
    type Provider = EphemeralOnly<ChaCha20Rng>;

    fn provider(&mut self) -> Self::Provider {
        let mut seed = [0u8; 32];
        self.master.fill_bytes(&mut seed);
        EphemeralOnly::new(ChaCha20Rng::from_seed(seed))
    }

    fn static_secret(&mut self) -> P256r1PrivateKey {
        P256r1PrivateKey::from_bytes(self.scalar)
            .expect("a validated static scalar always re-parses")
    }

    fn static_public(&self) -> P256r1PublicKey {
        self.public
    }
}

// ── An established session's crypto outputs ───────────────────────────────────

/// The crypto outputs of a completed handshake: the datagram send/receive halves,
/// the shared session id, and the two session indices plus the authenticated
/// remote static. The [`session`](crate::session) layer wraps this with the
/// replay window and timers.
pub struct Established {
    /// The sealing half — owns the monotonic send counter.
    pub send: DatagramSend<SlitherChannel>,
    /// The opening half — stateless in the counter (replay defence is ours).
    pub recv: DatagramRecv<SlitherChannel>,
    /// The shared session identifier (equal on both peers).
    pub session_id: SessionId,
    /// **Our** session index — inbound Data for this session carries it in
    /// `receiver_index`.
    pub our_index: u32,
    /// The **peer's** session index — we stamp it into outbound Data's
    /// `receiver_index`.
    pub peer_index: u32,
    /// The peer's long-term static, authenticated by the handshake.
    pub remote_static: P256r1PublicKey,
}

// ── Initiator ─────────────────────────────────────────────────────────────────

/// A paused IK initiator: msg1 has been built and sent, awaiting the responder's
/// msg2. Holds the typed await-msg2 state directly (the generated
/// [`IKInitiatorMsg2`]) alongside everything [`complete_init`] needs.
pub struct InitiatorPending<CP: CryptoKeyProvider<P256>> {
    /// The generated state awaiting msg2.
    msg2_state: IKInitiatorMsg2<CP>,
    /// Our chosen index for this attempt (the responder echoes it).
    pub sender_index: u32,
    /// The timestamp this attempt was built with.
    pub timestamp: Timestamp,
    /// The responder's static we dialled.
    pub remote_static: P256r1PublicKey,
}

/// Build a HandshakeInit packet and the paused initiator that completes on msg2.
///
/// `provider` is a **fresh** provider (fresh ephemeral); `static_secret` a fresh
/// owned copy of our static (consumed by the writer's `s` token);
/// `remote_static` the responder we dial (the IK `<- s` pre-message and the mac1
/// keying key); `sender_index` a random nonzero index; `timestamp` this attempt's
/// fresh timestamp, sealed into msg1's keyed payload tail by
/// [`write_message_1`](IKInitiatorMsg1::write_message_1). Returns the full
/// 196-byte Init packet and the [`InitiatorPending`]. Fresh ephemerals per
/// retransmit = a fresh initiator state per attempt, as ever.
pub fn build_init<CP>(
    provider: CP,
    static_secret: CP::PrivateKey,
    remote_static: P256r1PublicKey,
    sender_index: u32,
    timestamp: Timestamp,
) -> Result<(Vec<u8>, InitiatorPending<CP>), HsError>
where
    CP: DhProvider<P256>,
{
    // msg1 (`-> e, es, s, ss [12]`): one call writes the whole message, with
    // the 12-byte timestamp as the declared application payload.
    let (msg1, msg2_state) = IK::initiator(provider, PROLOGUE, remote_static)
        .write_message_1(static_secret, &timestamp.to_be_bytes())?;

    // Packet = header ‖ msg1 ‖ mac1 (keyed on the recipient = the responder).
    let header = InitHeader::new(sender_index);
    let mut packet = vec![0u8; INIT_PACKET_LEN];
    header.unchecked_write_to_slice(&mut packet[..InitHeader::SIZE]);
    packet[INIT_MSG_START..INIT_MAC_START].copy_from_slice(&msg1);
    let tag = mac::compute(&remote_static, &packet[..INIT_MAC_START]);
    packet[INIT_MAC_START..].copy_from_slice(&tag);

    Ok((
        packet,
        InitiatorPending {
            msg2_state,
            sender_index,
            timestamp,
            remote_static,
        },
    ))
}

/// Verify and complete an initiator handshake from the responder's `resp_packet`.
///
/// Checks the packet length, that its `receiver_index` echoes our `sender_index`,
/// and the mac1 (keyed on **our** static — we are the recipient of msg2) — all
/// before touching the Noise state. A forged or tampered msg2 fails the Noise
/// AEAD ([`HsError::Crypto`]); any structural or addressing failure is
/// [`HsError::Drop`].
pub fn complete_init<CP>(
    pending: InitiatorPending<CP>,
    own_static_public: &P256r1PublicKey,
    resp_packet: &[u8],
) -> Result<Established, HsError>
where
    CP: DhProvider<P256>,
{
    if resp_packet.len() != RESP_PACKET_LEN {
        return Err(HsError::Drop("resp: wrong length"));
    }
    let header = View::<RespHeader>::try_from_slice(&resp_packet[..RespHeader::SIZE])
        .map_err(|_| HsError::Drop("resp: bad header"))?
        .unpack();
    if header.receiver_index() != pending.sender_index {
        return Err(HsError::Drop("resp: receiver_index mismatch"));
    }
    // mac1 gate: the responder keyed it on OUR static (we are the recipient).
    if !mac::verify(
        own_static_public,
        &resp_packet[..RESP_MAC_START],
        &resp_packet[RESP_MAC_START..],
    ) {
        return Err(HsError::Drop("resp: mac1"));
    }

    let msg2: &[u8; IK::MSG2_SIZE] = resp_packet[RESP_MSG_START..RESP_MAC_START]
        .try_into()
        .expect("the length gate fixes the msg2 slice at IK::MSG2_SIZE bytes");
    let transport = pending.msg2_state.read_message_2(msg2)?;
    let session_id = transport.session_id().clone();
    // The epoch ratchet renews the transport keys on a counter-derived schedule
    // (both directions, same epoch size), so an idle session retires ageing key
    // material without a re-handshake. Byte-identical on the wire — the counter
    // header and ciphertext are unchanged; only the key schedule ratchets.
    let (send, recv) = transport.into_datagram_with_epoch(REKEY_EPOCH_MSGS);
    Ok(Established {
        send,
        recv,
        session_id,
        our_index: pending.sender_index,
        peer_index: header.sender_index(),
        remote_static: pending.remote_static,
    })
}

// ── Responder ─────────────────────────────────────────────────────────────────

/// An IK responder paused after an **accepted** read of msg1 — the initiator
/// passed the allow-list closure, the claim is **authenticated** (`ss` and the
/// tail's AEAD tag verified inside the read), and the timestamp is decrypted,
/// but msg2 is unwritten. Gate [`timestamp`](Self::timestamp) on the
/// [`TimestampGuard`], then [`accept`](Self::accept) to write msg2 — or
/// **drop** to reject with no msg2.
pub struct RespAccept<CP: CryptoKeyProvider<P256>> {
    /// The generated state that writes msg2.
    msg2_state: IKResponderMsg2<CP>,
    initiator_static: P256r1PublicKey,
    initiator_index: u32,
    timestamp: Timestamp,
}

impl<CP: CryptoKeyProvider<P256>> RespAccept<CP> {
    /// The initiator's static, **authenticated** — the `ss`-keyed tail tag
    /// verified inside the accepted read proves possession.
    pub fn initiator_static(&self) -> &P256r1PublicKey {
        &self.initiator_static
    }

    /// The initiator's session index (from the Init header).
    pub fn initiator_index(&self) -> u32 {
        self.initiator_index
    }

    /// The initiation timestamp, decrypted from msg1's application payload
    /// (authenticated by the tail's AEAD tag).
    pub fn timestamp(&self) -> Timestamp {
        self.timestamp
    }
}

impl<CP: DhProvider<P256>> RespAccept<CP> {
    /// Admit and complete: write msg2 and establish. `responder_index` is our
    /// fresh random nonzero index. Returns the 107-byte Resp packet and the
    /// [`Established`] crypto outputs. Call only for an admitted initiator;
    /// dropping `self` instead rejects with no msg2.
    pub fn accept(self, responder_index: u32) -> Result<(Vec<u8>, Established), HsError> {
        let (msg2, transport) = self.msg2_state.write_message_2()?;
        let session_id = transport.session_id().clone();

        let header = RespHeader::new(responder_index, self.initiator_index);
        let mut packet = vec![0u8; RESP_PACKET_LEN];
        header.unchecked_write_to_slice(&mut packet[..RespHeader::SIZE]);
        packet[RESP_MSG_START..RESP_MAC_START].copy_from_slice(&msg2);
        // mac1 keyed on the recipient = the initiator.
        let tag = mac::compute(&self.initiator_static, &packet[..RESP_MAC_START]);
        packet[RESP_MAC_START..].copy_from_slice(&tag);

        // Same epoch-ratcheting split as the initiator (see [`complete_init`]):
        // both peers pass the identical `REKEY_EPOCH_MSGS`, so the key schedules
        // stay in lockstep.
        let (send, recv) = transport.into_datagram_with_epoch(REKEY_EPOCH_MSGS);
        Ok((
            packet,
            Established {
                send,
                recv,
                session_id,
                our_index: responder_index,
                peer_index: self.initiator_index,
                remote_static: self.initiator_static,
            },
        ))
    }
}

/// Verify a HandshakeInit's mac1 (the DoS gate — before any DH), then read msg1
/// through the generated verification read
/// ([`read_message_1_with`](IKResponderMsg1::read_message_1_with)), with the
/// **allow-list as the closure**: the initiator's claimed static is handed to
/// it after the `es` DH and **before** `ss`, so an unlisted claim costs exactly
/// one DH ([`HsError::Unlisted`] — no `ss`, no timestamp decryption, no msg2;
/// the ruling, 2026/07/16). An admitted read pays `ss`, which closes msg1,
/// **authenticates the claim**, and decrypts the 12-byte timestamp payload,
/// pausing on the returned [`RespAccept`].
///
/// `provider` is a fresh provider; `own_static_public` keys the mac1 gate (we
/// are the recipient) and is the `<- s` pre-message's public half;
/// `static_secret` is our fresh static (consumed by the responder constructor);
/// `allow` is the set of permitted initiator statics (33-byte compressed). A
/// garbage or wrong-key packet is rejected at mac1 with **no** provider DH
/// performed ([`HsError::Drop`]); a packet whose encrypted static fails to open
/// dies at the `s` token, and a tampered payload ciphertext or a forged claim
/// of a listed static dies at the tail's AEAD tag (both [`HsError::Crypto`]).
pub fn accept_init<CP>(
    provider: CP,
    own_static_public: &P256r1PublicKey,
    static_secret: CP::PrivateKey,
    init_packet: &[u8],
    allow: &HashSet<[u8; 33]>,
) -> Result<RespAccept<CP>, HsError>
where
    CP: DhProvider<P256>,
{
    if init_packet.len() != INIT_PACKET_LEN {
        return Err(HsError::Drop("init: wrong length"));
    }
    // mac1 gate FIRST — before constructing the handshake or touching the provider.
    if !mac::verify(
        own_static_public,
        &init_packet[..INIT_MAC_START],
        &init_packet[INIT_MAC_START..],
    ) {
        return Err(HsError::Drop("init: mac1"));
    }
    let header = View::<InitHeader>::try_from_slice(&init_packet[..InitHeader::SIZE])
        .map_err(|_| HsError::Drop("init: bad header"))?
        .unpack();
    let initiator_index = header.sender_index();
    let msg1: &[u8; IK::MSG1_SIZE] = init_packet[INIT_MSG_START..INIT_MAC_START]
        .try_into()
        .expect("the length gate fixes the msg1 slice at IK::MSG1_SIZE bytes");

    // msg1 (`-> e, es, s, ss [12]`): the verification read drives `e`, the
    // `es` DH (the responder's first), and decrypts the CLAIMED static `s`,
    // then fires the closure BEFORE `ss` — an unlisted claim aborts at the
    // one-DH cost, and the payload is only ever decrypted on an accepted read.
    let (payload, msg2_state) = IK::responder(provider, PROLOGUE, static_secret)?
        .read_message_1_with(msg1, |claimed| {
            if allow.contains(&claimed.to_compressed()) {
                Ok(())
            } else {
                Err(HandshakeError::PeerRejected {
                    reason: "initiator static not on the allow-list".into(),
                })
            }
        })?;

    Ok(RespAccept {
        initiator_static: *msg2_state.remote_static(),
        msg2_state,
        initiator_index,
        timestamp: Timestamp::from_be_bytes(payload),
    })
}

// ── The per-static greatest-timestamp guard (initiation-replay defence) ────────

/// Per initiator static, the greatest initiation timestamp accepted so far.
///
/// A replayed HandshakeInit carries the same timestamp it did originally, so it is
/// **not greater** than the recorded value and is rejected. A genuine fresh
/// attempt (or retransmit) carries a strictly greater timestamp and is admitted.
/// Keyed by the 33-byte compressed static, and only ever consulted for an
/// **authenticated** initiator (post-`ss`, i.e. after [`accept_init`]'s accepted
/// read verified the tail tag), so an attacker cannot pollute the map under a
/// key it does not hold.
#[derive(Default)]
pub struct TimestampGuard {
    greatest: HashMap<[u8; 33], Timestamp>,
}

impl TimestampGuard {
    /// A fresh, empty guard.
    pub fn new() -> Self {
        Self::default()
    }

    /// Admit `timestamp` for `initiator` iff it is strictly greater than the
    /// greatest previously admitted for that static; on admission the greatest is
    /// advanced. Returns `false` (a replay / non-greater) without changing state.
    pub fn admit(&mut self, initiator: &P256r1PublicKey, timestamp: Timestamp) -> bool {
        let key = initiator.to_compressed();
        match self.greatest.get(&key) {
            Some(prev) if timestamp <= *prev => false,
            _ => {
                self.greatest.insert(key, timestamp);
                true
            }
        }
    }
}

/// Draw a random **nonzero** `u32` session index (0 is reserved), regenerating on
/// the astronomically rare zero draw.
pub fn random_index(rng: &mut ChaCha20Rng) -> u32 {
    loop {
        let index = rng.next_u32();
        if index != 0 {
            return index;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn identity(scalar_seed: u8, master_seed: u8) -> SoftwareIdentity {
        // A valid, non-degenerate scalar: fill with a byte, keep it in range.
        let mut scalar = [scalar_seed; 32];
        scalar[0] = 0x01; // keep well within [1, n-1]
        SoftwareIdentity::from_scalar(scalar, ChaCha20Rng::from_seed([master_seed; 32]))
            .expect("valid scalar")
    }

    /// An allow-list holding exactly `keys`.
    fn allow_of(keys: &[P256r1PublicKey]) -> HashSet<[u8; 33]> {
        keys.iter().map(|key| key.to_compressed()).collect()
    }

    /// Run one full in-process handshake and return both peers' crypto outputs.
    fn run_handshake(
        initiator: &mut SoftwareIdentity,
        responder: &mut SoftwareIdentity,
        rng: &mut ChaCha20Rng,
    ) -> (Established, Established) {
        let init_index = random_index(rng);
        let resp_index = random_index(rng);
        let ts = Timestamp {
            secs: 1_000,
            nanos: 7,
        };
        let (init_packet, pending) = build_init(
            initiator.provider(),
            initiator.static_secret(),
            responder.static_public(),
            init_index,
            ts,
        )
        .expect("build init");

        let allow = allow_of(&[initiator.static_public()]);
        let accept = accept_init(
            responder.provider(),
            &responder.static_public(),
            responder.static_secret(),
            &init_packet,
            &allow,
        )
        .expect("accept init");
        assert_eq!(accept.initiator_static(), &initiator.static_public());
        assert_eq!(accept.timestamp(), ts, "the decrypted payload timestamp");
        let (resp_packet, resp_est) = accept.accept(resp_index).expect("accept");

        let init_est =
            complete_init(pending, &initiator.static_public(), &resp_packet).expect("complete");
        (init_est, resp_est)
    }

    #[test]
    fn protocol_name_is_pinned() {
        // The exact string the handshake hashes into its transcript
        // (`Noise_{pattern}_{curve}_{cipher}_{hash}`): the generated pattern
        // is deliberately named `IK`, so the machines speak precisely the
        // protocol the classic descriptor did.
        assert_eq!(
            format!(
                "Noise_{}_{}_{}_{}",
                <SlitherChannel as hiss::noise::Pattern>::NAME,
                <P256 as hiss::curve::Curve>::NAME,
                <ChaChaPoly as hiss::noise::Cipher>::NAME,
                <Blake2b as hiss::noise::Hash>::NAME,
            ),
            "Noise_IK_P256_ChaChaPoly_BLAKE2b"
        );
    }

    #[test]
    fn handshake_agrees_on_session_and_indices() {
        let mut a = identity(0x11, 0xA1);
        let mut b = identity(0x22, 0xB2);
        let mut rng = ChaCha20Rng::from_seed([0xC3; 32]);
        let (init, resp) = run_handshake(&mut a, &mut b, &mut rng);
        assert_eq!(init.session_id.as_bytes(), resp.session_id.as_bytes());
        assert_eq!(init.our_index, resp.peer_index);
        assert_eq!(init.peer_index, resp.our_index);
        assert_eq!(init.remote_static, b.static_public());
        assert_eq!(resp.remote_static, a.static_public());
    }

    #[test]
    fn established_datagrams_round_trip() {
        let mut a = identity(0x11, 0xA1);
        let mut b = identity(0x22, 0xB2);
        let mut rng = ChaCha20Rng::from_seed([0xC3; 32]);
        // `recv` is now an epoch-ratcheting half, so `decrypt_at` takes
        // `&mut self` (hiss R0); the responder binding must be mutable.
        let (mut init, mut resp) = run_handshake(&mut a, &mut b, &mut rng);

        // A→B under the Data header AD.
        let ad = crate::wire::DataHeader::new(resp.our_index, 0).to_bytes();
        let mut ct = vec![0u8; 5 + crate::wire::AEAD_TAG_LEN];
        let (counter, n) = init
            .send
            .encrypt_next(&ad, b"hello", &mut ct)
            .expect("seal");
        assert_eq!(counter, 0);
        let mut pt = vec![0u8; n];
        let m = resp
            .recv
            .decrypt_at(counter, &ad, &ct[..n], &mut pt)
            .expect("open");
        assert_eq!(&pt[..m], b"hello");
    }

    /// The key ratchet crosses an epoch boundary transparently, and a datagram
    /// reordered back across that boundary still opens under the receiver's
    /// retained previous-epoch key (hiss keeps the current and the immediately
    /// preceding epoch keys). Driven at the session layer directly — no
    /// endpoint, no frame layer — so a full `REKEY_EPOCH_MSGS` boundary is
    /// crossed in-memory and fast.
    #[tokio::test]
    async fn epoch_boundary_delivers_and_reordered_straggler_opens() {
        use crate::session::{REKEY_EPOCH_MSGS, Session};
        use crate::wire::DataHeader;
        use tokio::time::Instant;

        let mut a = identity(0x11, 0xA1);
        let mut b = identity(0x22, 0xB2);
        let mut rng = ChaCha20Rng::from_seed([0xC3; 32]);
        let (init_est, resp_est) = run_handshake(&mut a, &mut b, &mut rng);

        let addr_a: std::net::SocketAddr = "127.0.0.1:1".parse().expect("addr");
        let addr_b: std::net::SocketAddr = "127.0.0.1:2".parse().expect("addr");
        let now = Instant::now();
        let mut sender = Session::new(init_est, addr_b, now);
        let mut receiver = Session::new(resp_est, addr_a, now);

        let epoch = REKEY_EPOCH_MSGS.get(); // 65_536
        // Seal one full epoch of DATA (send counters 0..epoch, all epoch 0),
        // holding back the LAST epoch-0 packet so it can arrive after the
        // boundary as a reordered straggler.
        let mut held = None;
        for c in 0..epoch {
            let payload = c.to_be_bytes();
            let packet = sender.seal(&payload, now).expect("seal");
            assert_eq!(
                DataHeader::parse(&packet).expect("data").0.counter(),
                c,
                "the mirrored counter tracks the hiss send counter"
            );
            if c == epoch - 1 {
                held = Some((packet, payload));
            } else {
                let got = receiver.open(&packet, addr_a, now).expect("open epoch 0");
                assert_eq!(got.payload, Some(payload.to_vec()));
            }
        }

        // The first epoch-1 packet (counter == epoch): the send key has ratcheted
        // forward, and opening it commits the receiver's ratchet to epoch 1,
        // retaining epoch 0 as the previous key.
        let boundary_payload = epoch.to_be_bytes();
        let boundary = sender
            .seal(&boundary_payload, now)
            .expect("seal across the boundary");
        assert_eq!(
            DataHeader::parse(&boundary).expect("data").0.counter(),
            epoch
        );
        let got = receiver.open(&boundary, addr_a, now).expect("open epoch 1");
        assert_eq!(got.payload, Some(boundary_payload.to_vec()));

        // The held-back epoch-0 packet, reordered to after the boundary, still
        // opens under the retained previous-epoch key — and, one behind the
        // greatest counter, is inside the 128-counter replay window, so it
        // delivers exactly once.
        let (straggler_packet, straggler_payload) = held.expect("held a packet");
        let got = receiver
            .open(&straggler_packet, addr_a, now)
            .expect("the previous-epoch straggler still opens");
        assert_eq!(got.payload, Some(straggler_payload.to_vec()));
    }

    /// The Noise §11.3 REKEY transform underlying the epoch ratchet:
    /// `Rekey(k) = ENCRYPT(k, 2^64 − 1, empty, zeros[32])[0..32]`. Byte-pins the
    /// ChaCha20-Poly1305 vector `REKEY(0^32)` (independently recomputed twice in
    /// review) — slither's ratchet key schedule stands on it. Computed through
    /// hiss's public `Cipher::encrypt`, the same primitive hiss's own
    /// `rekey_key` uses.
    #[test]
    fn rekey_transform_kat() {
        use hiss::noise::{ChaChaPoly, Cipher};

        let mut out = [0u8; 32 + 16]; // 32-byte "ciphertext" + 16-byte tag
        let n = ChaChaPoly::encrypt(&[0u8; 32], u64::MAX, &[], &[0u8; 32], &mut out)
            .expect("rekey encrypt");
        assert_eq!(n, 48);
        let hex: String = out[..32].iter().map(|b| format!("{b:02x}")).collect();
        assert_eq!(
            hex, "25ce5d37df19f3783185f2ffd5ab17fa3397c212f02d62fb1733e0b875b74c58",
            "REKEY(0^32) vector"
        );
    }

    #[test]
    fn msg_sizes_match_the_wire_pins() {
        // Test 13: the concrete on-wire sizes of msg1/msg2 for the P-256 suite.
        let mut a = identity(0x11, 0xA1);
        let mut b = identity(0x22, 0xB2);
        let ts = Timestamp { secs: 1, nanos: 1 };
        let (init_packet, pending) = build_init(
            a.provider(),
            a.static_secret(),
            b.static_public(),
            0x1234_5678,
            ts,
        )
        .expect("init");
        assert_eq!(init_packet.len(), INIT_PACKET_LEN);
        assert_eq!(init_packet.len(), 196);
        let allow = allow_of(&[a.static_public()]);
        let accept = accept_init(
            b.provider(),
            &b.static_public(),
            b.static_secret(),
            &init_packet,
            &allow,
        )
        .expect("accept");
        let (resp_packet, _est) = accept.accept(0x9abc_def0).expect("accept");
        assert_eq!(resp_packet.len(), RESP_PACKET_LEN);
        assert_eq!(resp_packet.len(), 107);
        let _ = pending;
    }

    #[test]
    fn tampered_payload_fails_then_clean_msg1_succeeds() {
        // Flipping one byte of the msg1 timestamp-payload ciphertext (recomputing
        // mac1, which is keyed on a PUBLIC key — an on-path attacker can) makes
        // the msg1 tail's AEAD tag fail inside the read: no RespAccept, so no
        // msg2.
        let mut a = identity(0x11, 0xA1);
        let mut b = identity(0x22, 0xB2);
        let ts = Timestamp { secs: 5, nanos: 5 };
        let (init_packet, _pending) = build_init(
            a.provider(),
            a.static_secret(),
            b.static_public(),
            0x1111_1111,
            ts,
        )
        .expect("init");
        // The payload ciphertext sits after the 6-byte header, the 65-byte
        // plaintext ephemeral, and the 81-byte encrypted static.
        let payload_off = InitHeader::SIZE + 65 + (65 + 16);
        let mut tampered = init_packet.clone();
        tampered[payload_off] ^= 0xFF;
        let tag = mac::compute(&b.static_public(), &tampered[..INIT_MAC_START]);
        tampered[INIT_MAC_START..].copy_from_slice(&tag);
        // The flip is past the encrypted static, so the read sails through the
        // allow-list closure and dies at the payload tail's AEAD tag.
        let allow = allow_of(&[a.static_public()]);
        let result = accept_init(
            b.provider(),
            &b.static_public(),
            b.static_secret(),
            &tampered,
            &allow,
        );
        assert!(
            matches!(result, Err(HsError::Crypto(_))),
            "a tampered payload ciphertext must fail the tail AEAD inside the read"
        );

        // A subsequent clean msg1 succeeds — the tamper poisoned nothing.
        let accept = accept_init(
            b.provider(),
            &b.static_public(),
            b.static_secret(),
            &init_packet,
            &allow,
        )
        .expect("the clean msg1 is accepted");
        assert_eq!(accept.initiator_static(), &a.static_public());
        assert_eq!(accept.timestamp(), ts);
    }

    #[test]
    fn responder_dh_cost_is_staged() {
        // The ruled cost property (2026/07/16), pinned on the responder's
        // provider at the macro read's stage boundaries: a rejected read costs
        // exactly the one `es` DH, an accepted read costs exactly `es` + `ss`,
        // and the msg2 write adds `ee` + `se`. The initiator runs on its own
        // (uncounted) provider, so its DHs cannot pollute the count.
        use std::sync::atomic::Ordering;

        let mut a = identity(0x11, 0xA1);
        let mut b = crate::testutil::CountingIdentity::new(0x22, 0xB2).expect("valid scalar");
        let dh_count = b.dh_count();
        let ts = Timestamp { secs: 3, nanos: 3 };
        let (init_packet, pending) = build_init(
            a.provider(),
            a.static_secret(),
            b.static_public(),
            0x3333_3333,
            ts,
        )
        .expect("init");
        assert_eq!(dh_count.load(Ordering::SeqCst), 0, "no responder DH yet");

        // An unlisted (empty allow-list) read: rejected by the closure after
        // `es`, before `ss` — exactly one DH, no RespAccept.
        let rejected = accept_init(
            b.provider(),
            &b.static_public(),
            b.static_secret(),
            &init_packet,
            &HashSet::new(),
        );
        assert!(matches!(rejected, Err(HsError::Unlisted)));
        assert_eq!(
            dh_count.load(Ordering::SeqCst),
            1,
            "a rejected read costs exactly one DH (`es`)"
        );

        // The same msg1, allow-listed: the accepted read pays `es` + `ss`.
        let allow = HashSet::from([a.static_public().to_compressed()]);
        let accept = accept_init(
            b.provider(),
            &b.static_public(),
            b.static_secret(),
            &init_packet,
            &allow,
        )
        .expect("accept");
        assert_eq!(
            dh_count.load(Ordering::SeqCst),
            1 + 2,
            "an accepted read costs exactly two DHs (`es` + `ss`)"
        );
        assert_eq!(accept.timestamp(), ts);

        let (resp_packet, _est) = accept.accept(0x4444_4444).expect("accept");
        assert_eq!(
            dh_count.load(Ordering::SeqCst),
            1 + 2 + 2,
            "the msg2 write adds `ee` + `se`"
        );

        // Completing the initiator exercises only ITS provider: the responder's
        // count must not move.
        let _ = complete_init(pending, &a.static_public(), &resp_packet).expect("complete");
        assert_eq!(dh_count.load(Ordering::SeqCst), 5);
    }

    #[test]
    fn timestamp_is_not_on_the_wire() {
        // The slither-level twin of hiss's confidentiality-position test: the
        // timestamp is encrypted into msg1's keyed tail, so a distinctive
        // timestamp's 12 encoded bytes must not appear verbatim anywhere in the
        // transmitted HandshakeInit datagram.
        let mut a = identity(0x11, 0xA1);
        let b = identity(0x22, 0xB2);
        let ts = Timestamp {
            secs: 0x0102_0304_0506_0708,
            nanos: 0x090A_0B0C,
        };
        let (init_packet, _pending) = build_init(
            a.provider(),
            a.static_secret(),
            b.static_public(),
            0x2222_2222,
            ts,
        )
        .expect("init");
        let needle = ts.to_be_bytes();
        assert!(
            !init_packet.windows(needle.len()).any(|w| w == needle),
            "the timestamp plaintext must not appear on the wire"
        );
    }

    #[test]
    fn golden_wire_is_byte_identical_to_the_pre_migration_driver() {
        // The migration's verdict test. These bytes were captured on
        // 2026/07/16 from the pre-migration build (this crate's classic
        // `SyncHandshake` driving, against hiss's pre-M0 payload driver) with
        // exactly these deterministic inputs; the macro-generated machines
        // must reproduce every byte of both handshake packets and the shared
        // session id.
        const GOLDEN_INIT: &str = concat!(
            "01011234567804af81fa4f9ab39d290845d385222ea36a4b11fd12388ab2b1b8",
            "f99be35f77b0fe0d6651d464dd901901e35d9810a9cc1d7595d53d16d99bbd5a",
            "1956c0058c7d29166c7fbd18261acfc8f21b86f83252cb51c443def5b576488b",
            "9303a632ba4942a39371a7b8d2d3d121e1ce38c939dc1d32a3510c739384c0e7",
            "04632cd4ea3727e11b1ddcd96e3596acff183f21e9b1ca19a7f6528e420bc176",
            "4b9cc29da6b0ee54dc8f8624a9e3bba2fd30a9b9dae305637f01343093fbcd15",
            "65fe4ac5",
        );
        const GOLDEN_RESP: &str = concat!(
            "02019abcdef01234567804d64771d34b9b1a760137674baddf70671cbdae6fb9",
            "860adab7adb8320d6872c454a97127a211048d8f5c103ff72ce0c94eeed4040c",
            "845349f852fc8bcc8771a7982722005c2def655769efe2e4811319ccac56ca3e",
            "abb614c2da2f536aef599c",
        );
        const GOLDEN_SID: &str = concat!(
            "0cafb77596d15484217a20a6ee81870e6c6461816c9692162a0cbad43fc88bda",
            "7414b8c8c3f27893a492c0fac79b0f4afa09a0e2aa8c49e87fe0a78da41dcb88",
        );

        fn hex(bytes: &[u8]) -> String {
            bytes.iter().map(|b| format!("{b:02x}")).collect()
        }

        let mut a = identity(0x11, 0xA1);
        let mut b = identity(0x22, 0xB2);
        let ts = Timestamp {
            secs: 0x0102_0304_0506_0708,
            nanos: 0x090A_0B0C,
        };
        let (init_packet, pending) = build_init(
            a.provider(),
            a.static_secret(),
            b.static_public(),
            0x1234_5678,
            ts,
        )
        .expect("init");
        assert_eq!(
            hex(&init_packet),
            GOLDEN_INIT,
            "the HandshakeInit packet must be byte-identical to the pre-migration wire"
        );

        let allow = allow_of(&[a.static_public()]);
        let accept = accept_init(
            b.provider(),
            &b.static_public(),
            b.static_secret(),
            &init_packet,
            &allow,
        )
        .expect("accept");
        assert_eq!(accept.timestamp(), ts);
        let (resp_packet, resp_est) = accept.accept(0x9abc_def0).expect("accept");
        assert_eq!(
            hex(&resp_packet),
            GOLDEN_RESP,
            "the HandshakeResp packet must be byte-identical to the pre-migration wire"
        );

        let init_est = complete_init(pending, &a.static_public(), &resp_packet).expect("complete");
        assert_eq!(
            init_est.session_id.as_bytes(),
            resp_est.session_id.as_bytes()
        );
        assert_eq!(
            hex(init_est.session_id.as_bytes()),
            GOLDEN_SID,
            "the transcript hash must match the pre-migration handshake"
        );
    }

    #[test]
    fn timestamp_guard_rejects_non_greater() {
        let a = identity(0x11, 0xA1);
        let pubkey = a.static_public();
        let mut guard = TimestampGuard::new();
        let t1 = Timestamp {
            secs: 100,
            nanos: 0,
        };
        let t2 = Timestamp {
            secs: 100,
            nanos: 1,
        };
        assert!(guard.admit(&pubkey, t1));
        assert!(
            !guard.admit(&pubkey, t1),
            "a replay of the same timestamp is rejected"
        );
        assert!(
            !guard.admit(&pubkey, Timestamp { secs: 99, nanos: 0 }),
            "older rejected"
        );
        assert!(
            guard.admit(&pubkey, t2),
            "a strictly greater timestamp is admitted"
        );
    }
}
